services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    labels:
      - "category=utility"
